on:
  push:
    branches:
      - master

name: Build Artifacts
jobs:
  build:
    name: Build Apps (iOS/Android)
    runs-on: macos-latest
    steps:
      - name: ğŸ“¤ Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: ğŸ›’ Checkout repository
        uses: actions/checkout@v1
      - name: â˜• Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: ğŸ¦ Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: ğŸº Install pub Dependencies
        run: flutter pub get
      - name: ğŸ§ª Run Tests
        run: flutter test
      - name: ğŸ¤– Build Android App
        run: flutter build apk --split-per-abi
      - name: ğŸ Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: ğŸ‰ Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa'
